#!/usr/bin/env bash
set -euo pipefail

# Deploy script. Run this ON the production server, from inside the repo clone.
#
#   ./scripts/deploy.sh
#
# Does: git pull -> go build -> generate/keep gateway API key (run/deploy.env)
#        -> pm2 startOrReload -> pm2 save
#
# Requires: Go, pm2, and a clone of the repo. Set an explicit key with:
#   GATEWAY_API_KEY=<your-key> ./scripts/deploy.sh

ROOT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [[ ! -d .git ]]; then
  echo "[deploy] not a git checkout; skipping pull." >&2
else
  echo "[deploy] pulling latest..."
  git pull --ff-only
fi

if ! command -v go >/dev/null 2>&1; then
  echo "[deploy] ERROR: go not found on PATH. Install Go first (see go.mod for the version)." >&2
  exit 1
fi
if ! command -v pm2 >/dev/null 2>&1; then
  echo "[deploy] ERROR: pm2 not found on PATH." >&2
  exit 1
fi

echo "[deploy] building binaries..."
./scripts/build.sh

RUN_DIR="run"
mkdir -p "$RUN_DIR"

ENV_FILE="$RUN_DIR/deploy.env"
if [[ -f "$ENV_FILE" ]]; then
  echo "[deploy] reusing existing $ENV_FILE"
else
  KEY="${GATEWAY_API_KEY:-$(openssl rand -hex 24)}"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# The gateway only accepts the /api/servers registration call with this key.
FOUNDRY_GATEWAY_API_KEY=$KEY
EOF
  chmod 600 "$ENV_FILE"
  echo "[deploy] wrote new API key to $ENV_FILE (keep it secret)"
fi

echo "[deploy] starting/reloading processes..."
pm2 startOrReload ecosystem.config.cjs --update-env

echo "[deploy] saving pm2 process list..."
pm2 save

echo ""
echo "==> Done"
pm2 status
echo ""
echo "Next: point your reverse proxy at 127.0.0.1:4283 (gateway) and"
echo "      127.0.0.1:63566 (world ws), then set the public ws_url in"
echo "      deploy/servers.prod.yaml to wss://<your-world-domain>/ws"
echo "      and re-run ./scripts/deploy.sh"